# Generated by Django 6.0.2 on 2026-03-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0002_service_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text="Customer's preferred service date", null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text="Customer's preferred service time", null=True),
        ),
    ]
