# Generated by Django 6.0.2 on 2026-04-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0003_transaction_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_package',
            field=models.BooleanField(default=False, help_text='Mark as a package deal'),
        ),
    ]
